# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'leico/autodate.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''

[[plugins]]
repo = 'airblade/vim-router'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
rev = "release"
hook_add = """
source ~/.config/nvim/plugins/coc.rc.vim
"""

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'frazrepo/vim-rainbow'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

#[[plugins]]
#repo = 'pangloss/vim-javascript'

#[[plugins]]
#repo = 'leafgarland/typescript-vim'

#[[plugins]]
#repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
repo = 'styled-components/vim-styled-components'

[[plugins]]
repo = 'jparise/vim-graphql'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  set background=dark
  autocmd VimEnter * ++nested colorscheme gruvbox
'''

[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

